### ISSUE TITLE
Remove cable cutout from electronics case

### ISSUE THREAD

**Issue by mfillmer** [urban-smart-grow/AeroTower#7]
The cable cutout on the bottom of the [electronics case](https://github.com/urban-smart-grow/AeroTower/blob/167bae4f82490244af1cde0fe1fb61e13ed3d9c0/src/head_electronics_case.py) is not longer needed.
It can be removed and the extra height can be removed, resulting in a base height of 2mm.

**Comment by tekikaito** [comment]
Why is it possible to do without the inlets?

**Comment by tekikaito** [comment]
Can all the inlets be removed? (front, side and bottom)

**Comment by mfillmer** [comment]
Hi, good questions!

Only the channels on the bottom of the case can be removed, as the cables do not get squeezed at this side.
It is also the only side, where extra material is added to make the cutout possible. 

Below are images for further illustration.

![PXL_20230311_074129744 MP](https://user-images.githubusercontent.com/12849528/224472202-93397664-b3e1-4311-86d0-0604eb43c41e.jpg)
![PXL_20230311_074158463](https://user-images.githubusercontent.com/12849528/224472205-cfd87565-7ada-4627-b9f7-f9fbd79f9c10.jpg)
![PXL_20230311_074227971](https://user-images.githubusercontent.com/12849528/224472213-b8cc7832-bb5e-41dc-ae13-75fb3ecab185.jpg)
![PXL_20230311_074212178 MP](https://user-images.githubusercontent.com/12849528/224472207-f3efdd0a-dccc-440e-a5f4-46f37e17e650.jpg)
